[versions]
kotlin = "2.4.10"
kotter = "1.4.0"
graalvm = "1.1.6"

[libraries]
kotter-jvm = { module = "com.varabyte.kotter:kotter", version.ref = "kotter" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm" }
